-- AlterTable
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveIsRunning" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveLevel" INTEGER;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveSmallBlind" INTEGER;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveBigBlind" INTEGER;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveAnte" INTEGER;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveNextBreakInSec" INTEGER;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "livePlayersIn" INTEGER;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "liveUpdatedAt" TIMESTAMP(3);
